FROM tomcat:9.0.70-jdk11
LABEL myinno.authors="msa.myinno@gmail.com"
RUN apt-get update&& apt-get install -y curl vim
RUN echo "org.apache.jasper.servlet.TldScanner.level = SEVERE" >> /usr/local/tomcat/logging.properties
RUN echo "org.apache.jasper.compiler.TldLocationsCache.level = FINE" >> /usr/local/tomcat/logging.properties
RUN echo "org.apache.jasper.servlet.TldScanner.level = FINE" >> /usr/local/tomcat/logging.properties
COPY ./hello-world.war /usr/local/tomcat/webapps
EXPOSE 8080