version: '2'

services:

## docker + SSH + Ubuntu
  ssh-docker:
    build: UbuntuSshd
    container_name: ssh-docker
    command: /usr/sbin/sshd -D
#    mem_limit: 550M
    privileged: true
    networks:
      - jenkins
    networks:
      default:
        aliases:
          - docker

    ports:
      - '2202:22'
      - '8083:8080'
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - /d/APP/@inflearn/202212-JenkinsCICD/jenkins_SHARE/certs:/certs/client
      - /d/APP/@inflearn/202212-JenkinsCICD/jenkins_SHARE/sshhome:/home      
      
  docker-dind:
    image: docker:dind
    mem_limit: 200m
    mem_reservation: 150m
    privileged: true
#    detach: true
#    rm: true
    volumes:
      - /d/APP/@inflearn/202212-JenkinsCICD/jenkins_SHARE/certs:/certs/client
      - /d/APP/@inflearn/202212-JenkinsCICD/jenkins_SHARE/var:/var/jenkins_home
    ports:
      - 2376:2376
    networks:
      - jenkins
    networks:
      default:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs      