version: '2'

services:

## docker + SSH + Ubuntu
  ssh-docker:
    build: UbuntuSshd
    container_name: ssh-docker
#    command: /usr/sbin/sshd -D
#    mem_limit: 550M
    privileged: true
#    networks:
#      - jenkins
    ports:
      - '2202:22'
      - '8083:8080'
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ${DIRPATH}/jenkins_SHARE/certs:/certs/client
      - ${DIRPATH}/jenkins_SHARE/sshhome:/home      
      - /var/run/docker.sock:/var/run/docker.sock
