version: '2'

services:
  jenkins-docker:
    image: docker:dind
    container_name: dind
#    mem_limit: 100m
#    mem_reservation: 60m
    privileged: true
    volumes:
      - ${DIRPATH}/jenkins_SHARE/certs:/certs/client
      - ${DIRPATH}/jenkins_SHARE/var:/var/jenkins_home
    ports:
      - 2376:2376
    networks:
      - jenkins
    networks:
      default:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs 
     
## jenkins-blueocean
  jenkins-blueocean:
    build: jenkins
    container_name: jenkins
#    command: /usr/sbin/sshd -D
    mem_limit: 1024m
    mem_reservation: 600m
    privileged: true
#    networks:
#      - jenkins
#    networks:
#      default:
#        aliases:
#          - docker
    ports:
      - 8099:8080
      - 50000:50000
      - 2201:22
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS="-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
#      - JAVA_OPTS="-Xmx700m"
      - TZ=Asia/Seoul
    volumes:
      - ${DIRPATH}/jenkins_SHARE/certs:/certs/client
      - ${DIRPATH}/jenkins_SHARE/var:/var/jenkins_home
      - ${DIRPATH}/jenkins_SHARE/home:/home
    restart: on-failure

## docker + SSH + Ubuntu
  ssh-docker:
    build: UbuntuSshd
    container_name: ssh-docker
#    command: /usr/sbin/sshd -D
#    mem_limit: 550M
    privileged: true
#    networks:
#      - jenkins
#    networks:
#      default:
#        aliases:
#          - docker
    ports:
      - '2202:22'
      - '8083:8080'
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - TZ=Asia/Seoul
    volumes:
      - ${DIRPATH}/jenkins_SHARE/certs:/certs/client
      - ${DIRPATH}/jenkins_SHARE/sshhome:/home      
#      - /var/run/docker.sock:/var/run/docker.sock