version: '2'

services:
  ansible:
    build:
      context: ansible
      dockerfile: Dockerfile_ansible
    container_name: my-ansible    
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /d/APP/@inflearn/202212-JenkinsCICD/jenkins_SHARE/certs:/certs/client      
      - /d/APP/@inflearn/202212-JenkinsCICD/jenkins_SHARE/var:/var/jenkins_home
    ports:
      - 2205:22
      - 8085:8080
    networks:
      - jenkins
    networks:
      default:
        aliases:
          - docker
    environment:
      - container=docker
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1      
      - TZ=Asia/Seoul
